### ISSUE TITLE
Vector删除操作可能会内存泄露

### ISSUE THREAD

**Issue by goldpasser** [chen3feng/stl4go#117]
https://github.com/golang/go/issues/54650
https://natan36.medium.com/gos-memory-leak-caused-by-slice-742d668bcfa6
如果Vector存放的是指针，删除有可能内存泄露。

**Comment by chen3feng** [comment]
是的

**Comment by chen3feng** [comment]
有什么好的方案吗？

**Comment by chen3feng** [comment]
Pop和Remove确实会，我改为用零值填充
